### ISSUE TITLE
build fails requiring a compiler version newer then the latest release of Conan

### ISSUE THREAD

**Issue by silverhikari** [Audacium/audacium#109]
**Describe the bug**
when building the latest commit of Audacium, a error appears that cause the build to fail, which is caused by the "compiler.version" setting being 12 while the highest the latest version of Conan will go up to is "11.1"

**To Reproduce**
1. git pull or clone the repository
2. build cmake with configure.sh or through commandline
3. error appears

**Expected behavior**
 - OS: Manjaro/Linux
 - Version : git commit latest
 - conan: 1.48.1

**Comment by silverhikari** [comment]
this has been tested with conan-git which also has the error appear

**Comment by crsib** [comment]
I think you need to delete `~/.conan/settings.yml` and the error will be gone

**Comment by silverhikari** [comment]
@crsib yes that fixed it, thank you!
